spring:
  datasource:
    url: 'jdbc:h2:mem:medical_db'
    username: "medical"
    password: 'medical2}'
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    com.medical: DEBUG
